! ================================================================================ 
! Notice : Copyright (C) 2017, Devuna
!          Distributed under LGPLv3 (http://www.gnu.org/licenses/lgpl.html) 
! 
!    This file is part of Devuna-Common (https://github.com/Devuna/Devuna-Common) 
! 
!    Devuna-Common is free software: you can redistribute it and/or modify 
!    it under the terms of the GNU General Public License as published by 
!    the Free Software Foundation, either version 3 of the License, or 
!    (at your option) any later version. 
! 
!    Devuna-Common is distributed in the hope that it will be useful, 
!    but WITHOUT ANY WARRANTY; without even the implied warranty of 
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
!    GNU General Public License for more details. 
! 
!    You should have received a copy of the GNU General Public License 
!    along with Devuna-Common.  If not, see <http://www.gnu.org/licenses/>. 
! ================================================================================

DEFAULTWINDOWCOLOR          EQUATE(0C08080H)
DEFAULTBROWSECOLOR          EQUATE(0C08080H)
DEFAULTFORMCOLOR            EQUATE(0C08080H)
DEFAULTPANELCOLOR           EQUATE(0DDBBBBH)
DEFAULTSHEETCOLOR           EQUATE(0DDBBBBH)
DEFAULTPROMPTCOLOR          EQUATE(COLOR:NONE)
DEFAULTSTRINGCOLOR          EQUATE(COLOR:NONE)
DEFAULTBACKCOLOR            EQUATE(COLOR:WHITE)
DEFAULTBACKSELECTEDCOLOR    EQUATE(COLOR:NONE)
DEFAULTTEXTCOLOR            EQUATE(COLOR:NONE)
DEFAULTTEXTSELECTEDCOLOR    EQUATE(COLOR:NONE)
